### ISSUE TITLE
Errors with 'element' and 'getdata'

### ISSUE THREAD

**Issue by keflavich** [AtomPy/AtomPy#2]
I'm trying to use atompy but am running in to many errors following the examples from your paper:

```
In [2]: import atompy
Initializing AtomPy...
No handlers could be found for logger "apiclient.discovery"
AtomPy ready!

In [3]: atompy.element(2)
Traceback (most recent call last):
  File "<ipython-input-3-6988721584e2>", line 1, in <module>
    atompy.element(2)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/atompy/__init__.py", line 16, in element
    return Refs.element(Z)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/atompy/refs.py", line 40, in element
    return (ion['Element'],ion['Symbol'])
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/pandas/core/series.py", line 484, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/pandas/core/index.py", line 1210, in get_value
    raise e1
KeyError: 'Symbol'
```

and if I try to `getdata`:

```
In [4]: atompy.getdata(26,25)
Retrieving workbook: 26_25
Traceback (most recent call last):
  File "<ipython-input-4-f3155cb1c850>", line 1, in <module>
    atompy.getdata(26,25)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/atompy/__init__.py", line 176, in getdata
    file = API.getFile(filename)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/atompy/DownloadAPI.py", line 175, in getFile
    GDClient = getGDClient()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/atompy/DownloadAPI.py", line 161, in getGDClient
    gd_client.ProgrammaticLogin()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/gdata/service.py", line 793, in ProgrammaticLogin
    raise BadAuthentication, 'Incorrect username or password'
BadAuthentication: Incorrect username or password
```

Are there additional steps I need to take to install the package?

**Comment by LucasBoswell** [comment]
Thank you for contacting us about this issue. I am able to duplicate the same results on my own machine, so it is on the server side of things that the issue resides. It is now being investigated.

**Comment by LucasBoswell** [comment]
The errors presented have been corrected. It seems Google Drive's security was overprotective. If you have any further issues please do not hesitate to let us know.
